-- Basic 
	require('core.plugins')
	require('core.mappings')
	require('core.theme')
	require('core.configs')
-- Plugins 
	require('plugins.neotree')
	require('plugins.treesitter')
	require('plugins.lsp')
	require('plugins.mason')
	require('plugins.telescope')
	require('plugins.nullls')
	require('plugins.autopairs')
	require('plugins.bufferline')
	require('plugins.dashboard')
	require('plugins.comments')
	require('plugins.gitsigns')
	require('plugins.lualine')
	require('plugins.hop')
	require('plugins.outline')
	require('plugins.toggleterm')
	require('plugins.whichkey')
	require('plugins.micons')
	require('plugins.mnd')
	require('plugins.nvimdapui')
	require('plugins.cmp')
	require('plugins.nvim-dap')
